name: football_app
description: A new Flutter project for Ruangguru Tech-home test

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.4.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  http: ^0.13.3
  injectable: ^1.5.0
  intl: ^0.17.0
  json_serializable: ^5.0.2
  lottie: ^1.2.1

dev_dependencies:
  auto_route_generator: ^2.4.0
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/
